# Generated by Django 4.1.3 on 2022-12-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystrom_rest", "0002_mystromdevice_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="mystromresult",
            name="source",
            field=models.IntegerField(default=1),
        ),
    ]
